import MainLayout from "@/layouts/MainLayout";
import style from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className={style.flexCenter}>
          <Image
            style={{ opacity: "0.7" }}
            alt="etherium"
            width={700}
            height={600}
            src={"/main.png"}
          />
        </div>
      </MainLayout>
    </>
  );
}
